baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
lastmod = true
enableGitalk = true


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params.gitalk]
  clientID = "Your client ID"
  clientSecret = "Your client secret"
  repo = "repo"
  owner = "Your Github username"
  admin = "Your Github username"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 30
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false
